name: Deploy test Azure Infrastructure

on:
  workflow_dispatch:
    
jobs:
  Deploy_test:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Deployment
      uses: parallo-mattallford/workflowtest/.github/templates@main
      with:
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
        subscription_id: 8c6ccaa9-9f43-4f74-a91e-12a9f922d72c
        environment_name: test
        location: Australia East