name: Deploy production Azure Infrastructure

on:
  workflow_dispatch:
    
jobs:
  Deploy_production:
    uses: parallo-mattallford/workflowtest/.github/workflows/deployment-template.yml@main
    with:
      subscription_id: 7ecbc33f-d50e-4339-a26b-eb307001d280
      environment_name: production
      location: Australia East
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}